version: 2.1

executors:
  openapi-generator-cli:
    docker:
      - image: openapitools/openapi-generator-cli:v5.0.1

jobs:
  foo:
    executor:
      name: openapi-generator-cli
  steps:
    - checkout
    - run:
        name: foo
        command: |
          echo "foo"

workflows:
  version: 2
  ci:
    jobs:
      - foo
