version: 2.1

executors:
  openapi-generator-cli:
    docker:
      - image: openapitools/openapi-generator-cli:v5.0.1

jobs:
  generate-client:
    executor:
      name: openapi-generator-cli
    steps:
      - checkout
      - run:
          name: install-packages
          command: |
            apk update
            apk add git
      - run:
          name: generate-client
          command: |
            docker-entrypoint.sh \
            generate \
            --input-spec ./openapi.yaml \
            --generator-name typescript-axios \
            --output ./api-client \
            --config ./api.json \
            --additional-properties=useSingleRequestParameter=true
            git status

workflows:
  version: 2
  ci:
    jobs:
      - generate-client
